projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: https://protected-island-21893.herokuapp.com/
#        default: http://localhost:4000/
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml